server:
  port: 5500
  host: localhost
  env: development
  upload_folder: ./upload
  sql_folder: ./internal/db/sql
database:
  timeout: 5s
  pool_size: 10
services:
  auth:
    access_token_duration: 15m
    refresh_token_duration: 168h
